package: nb_conda_kernels

platform:
  - linux-64
  - osx-64
  - win-64
  - linux-32
  - win-32

engine:
  - python=2.7
  - python=3.4
  - python=3.5

script:
  - conda build conda.recipe -c anaconda-nb-extensions/label/dev -c bokeh

build_targets: conda
