package: nb_conda_kernels

platform:
  - linux-64
  - osx-64
  - win-64

engine:
  - python=2.7
  - python=3.4
  - python=3.5

script:
  - conda build conda.recipe -c javascript -c r

build_targets: conda
