# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

- job: 'Build'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - task: CondaEnvironment@1
    inputs:
      updateConda: no
      packageSpecs: 'conda-verify conda-build ipykernel anaconda-client'

  - script: |
      conda env create -f conda-recipe/testenv1.yaml
      conda env create -f conda-recipe/testenv2.yaml
      conda info -a
    displayName: 'Create test environments'

  - script: conda build conda-recipe --python=$(python.version)
    displayName: 'Build package'

- job: 'Upload'
  dependsOn: 'Build'
  pool: 
    vmimage: 'Linux Preview'

  steps:
  - script: anaconda --verbose --token $ANACONDA_TOKEN upload --user jupycon $CONDA_PREFIX/conda-bld/*/*.tar.bz2 --force
    displayName: 'Upload to anaconda.org'
