name: nb_conda_kernels
channels:
  - javascript
  - anaconda-nb-extensions/label/dev
  - r
dependencies:
  - anaconda-client
  - coverage
  - flake8
  - mock
  - nodejs
  - nose
  - notebook
  - r-essentials
