{% set version = "2.1.0" %}
{% set gh_org = "Anaconda-Platform" %}
{% set gh_repo = "nb_conda_kernels" %}

package:
  name: {{ gh_repo }}
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jupyter_client >=4.2

test:
  imports:
    - nb_conda_kernels

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Launch Jupyter kernels for any installed conda environment.'
