{% set data = load_setup_py_data() %}

package:
  name: nb_conda_kernels
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools
  run:
    - python
    - jupyter_client >=4.2

test:
  source_files:
    - setup.cfg
  requires:
    - notebook
    - r-irkernel
    - nose
    - coverage
    - mock
    - requests
    - nodejs # [py3k]
  commands:
    - npx -p phantomjs -p casperjs nosetests nb_conda_kernels # [py3k]
    - nosetests nb_conda_kernels --exclude=test_notebook # [py2k]

about:
  home: https://github.com/Anaconda-Platform/nb_conda_kernels
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Launch Jupyter kernels for any installed conda environment.'
