package:
  name: nb_conda_kernels
  version: "0.1.1"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', '0') }}

requirements:
  build:
    - python
  run:
    - python
    - nb_config_manager
    # Beta solving a py2 bug on last traitlets
    - traitlets ==4.1.0b1

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/nb_conda_kernels
  license: BSD
  license_file: LICENSE
