package:
  name: nb_conda_kernels
  version: "1.0.0"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', '0') }}

requirements:
  build:
    - python
  run:
    - python
    - notebook >4.1
    - traitlets >=4.1.0

test:
  requires:
    - notebook
    - python
    - requests
    - nose
    - selenium

source:
  git_url: ../

about:
  home: https://github.com/Anaconda-Server/nb_conda_kernels
  license: BSD
