package:
  name: nb_conda_kernels
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

requirements:
  build:
    - python
  run:
    - python
    - notebook >=4.2.0
    - traitlets >=4.1.0

test:
  requires:
    - notebook >=4.2.0
    - python
    - requests
    - nose
    - selenium

source:
  git_url: ../

about:
  home: https://github.com/Anaconda-Platform/nb_conda_kernels
  license: BSD
